version: "3.9"

services:
  backend:
    build: ./backend
    container_name: schedule-backend-dev
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build: ./frontend
    container_name: schedule-frontend-dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
