services:
  # mysql:
  #   image: mysql:8.0
  #   container_name: schedule-mysql
  #   restart: always
  #   ports:
  #     - "3307:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: db_edt_p
  #     MYSQL_USER: orion
  #     MYSQL_PASSWORD: orion3691
  #   volumes:
  #     - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: schedule-backend-dev
    ports:
      - "8000:8000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8000
      - ConnectionStrings__DefaultConnection=Server=mysql-fa8f43c-hghjbjjkhjhuifhjg.g.aivencloud.com;Port=11328;Database=db_edt_p;User=avnadmin;Password=AVNS_kN0s7eSogKTNZ_uQEl8;SslMode=Required;
    # depends_on:
    #   - mysql

  frontend:
    build: ./frontend
    container_name: schedule-frontend-dev
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
# volumes:
#   mysql_data:
