version: "3.9"

services:
  backend:
    build: ./backend
    container_name: schedule-backend-prod
    ports:
      - "8000:8000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build: ./frontend
    container_name: schedule-frontend-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
