apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedconnect-api
spec:
  replicas: 1

  selector:
    matchLabels:
      app: schedconnect-api

  template:
    metadata:
      labels:
        app: schedconnect-api

    spec:
      containers:
        - name: schedconnect-api
          image: juliannot3691/schedconnect-api:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: backend-secrets-k8s
                  key: db-connection

            - name: Cors__Origins
              value: "http://app.local"

            - name: Jwt__Issuer
              value: "http://app.local"

            - name: Jwt__Audience
              value: "http://app.local"

      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: schedconnect-api

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

  type: ClusterIP
