apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
        - name: backend-api
          image: juliannot3691/backend-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: backend-secrets-k8s
                  key: db-connection

            - name: Cors__Origins
              value: "http://frontend-service"

            - name: Jwt__Issuer
              value: "http://backend-service"

            - name: Jwt__Audience
              value: "http://backend-service"

      imagePullSecrets:
        - name: regcred
