apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-react
  template:
    metadata:
      labels:
        app: frontend-react
    spec:
      containers:
        - name: frontend-react
          image: orion@3691/frontend-react:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred  # Secret créé pour Docker Hub

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-react
  ports:
    - port: 80
      targetPort: 80
  type: NodePort